language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    
env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1
    
matrix:
    include:
        - php: 5.3
          env: WP_VERSION=latest WP_MULTISITE=0
          dist: precise
        - php: 5.3
          env: WP_VERSION=latest WP_MULTISITE=1
          dist: precise
        - php: 5.3
          env: WP_VERSION=3.8 WP_MULTISITE=0
          dist: precise
        - php: 5.3
          env: WP_VERSION=3.8 WP_MULTISITE=1
          dist: precise

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
